config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  patch '/users/:id', to: 'users#update_teacher_status', as: 'teacher'

  resources :users, only: [:show] do
    resources :bookings, except: [:new, :show]
  end

  resources :dives, only: [:index, :show]

  namespace :guide do
    resources :dives, except: [:show]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user # Renvoie vers les clients (pas le teacher)
  belongs_to :dive
  validate :quantity_cannot_be_greater_than_capacity
  # valider que quantity <= self.dive.capacity ? utiliser callback ?

  def quantity_cannot_be_greater_than_capacity
    errors.add(:quantity, "can't be greater than the capacity") unless quantity <= self.dive.capacity
  end
end

app/models/dive.rb
class Dive < ApplicationRecord

  belongs_to :user # Renvoie vers le teacher
  has_many :bookings, dependent: :destroy
  validates :location, :capacity, :price, :depth_required, :description, presence: true
  validates :depth_required, inclusion: { in: (0..40) }
  validate :user_is_a_teacher
  has_attachments :photos, maximum: 2
  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  def user_is_a_teacher
    errors.add(:user, "is not a teacher") unless user.teacher == true
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :dives, dependent: :destroy
  validates :name, :max_depth, presence: true
  validates :level, inclusion: { in: (1..5) }
  validate :user_can_be_a_teacher
  validates :bio, presence: true, if: :teacher
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attachment :photo

  def photo_url
    if photo.present?
      photo.path
    else
      "http://placehold.it/40"
    end
  end


  protected

  def user_can_be_a_teacher
    if level < 4
      errors.add(:teacher, "can't be a teacher") unless teacher == false
    else
      true
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:level, :max_depth, :name, :email, :password, :password_confirmation, :photo)
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = current_user.bookings
  end

  def show
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.date = Date.strptime(booking_params[:date], '%m/%d/%Y')
    @booking.user = current_user
    if @booking.save
      redirect_to user_bookings_path, notice: "Your booking has been successfully created"
    else
      @modal_open = true
      redirect_to dive_path(@booking.dive), alert: "It didn't work"
      # render 'dives/show', alert: "It didn't work"
    end
  end

  def update
    if @booking.update(booking_params)
      redirect_to user_bookings_path(current_user), notice: "Your booking has been successfully modified"
    else
      render user_bookings_path(current_user), alert: "Your edit didn't work"
    end
  end

  # def create
  #     # [...]
  #     if @review.save
  #       respond_to do |format|
  #         format.html { redirect_to restaurant_path(@restaurant) }
  #         format.js  # <-- will render `app/views/reviews/create.js.erb`
  #       end
  #     else
  #       respond_to do |format|
  #         format.html { render 'restaurants/show' }
  #         format.js  # <-- idem
  #       end
  #     end
  #   end

  def destroy
    @booking.destroy
    redirect_to user_bookings_path, notice: 'Booking was successfully canceled.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params
      .require(:booking)
      .permit(:quantity, :dive_id, :review, :rating, :status, :date)
    # rating ? & review ?
    # Pas pour la création et la modification
    # avant qu'ils aient fait leur plongée
  end
end

app/controllers/dives_controller.rb
class DivesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index

      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    @dives = Dive.all

    filter = nil
    filter = Dive.near(params[:location], 10) \
      if params[:location] != nil && params[:location] != ""
    @dives = filter if filter != nil

    filter = nil
    filter = @dives.where("capacity >= ?", params[:capacity]) \
      if params[:capacity] != nil && params[:capacity] != ""
    @dives = filter if filter != nil

    filter = nil
    filter = @dives.where("price <= ?", params[:price]) \
      if params[:price] != nil && params[:price] != ""
    @dives = filter if filter != nil

    filter = nil
    filter = @dives.where("depth_required <= ?", params[:max_depth]) \
      if params[:max_depth] != nil && params[:max_depth] != ""
    @dives = filter if filter != nil

    @dives = @dives.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@dives) do |dive, marker|
      marker.lat dive.latitude
      marker.lng dive.longitude
    end
  end

  def show
    @dive = Dive.find(params[:id])
    @unavailability = []
    @today = Date.current.strftime('%m/%d/%Y')
    @dive.user.dives.each do |dive|
      dive.bookings.each do |booking|
        @unavailability << booking.date.strftime('%m/%d/%Y')
      end
    end
    @booking = Booking.new
  end
end

app/controllers/guide/dives_controller.rb
class Guide::DivesController < ApplicationController
  before_action :confirm_guide_authentification

  def index
    # Let's anticipate on next week (with login)
    @dives = current_user.dives
  end

  def new
    @dive = Dive.new
  end

  def create
    @dive = Dive.new(dive_params)
    @dive.user = current_user
    if @dive.save
      redirect_to dive_path(@dive)
    else
      render :new
    end
  end

  def edit
    @dive = Dive.find(params[:id])
  end

  def update
    @dive = Dive.find(params[:id])
    if @dive.update(dive_params)
      redirect_to guide_dives_path
    else
      render :edit
    end
  end

  def destroy
    @dive = Dive.find(params[:id])
    # redirect_to profile_dives_path
    ## Rediriger vers la index de Dives namespacé dans #profile
  end


  protected

  def dive_params
    params
      .require(:dive)
      .permit(
        :location,
        :capacity,
        :price,
        :depth_required,
        :description,
        photos: []
      )
  end

  def confirm_guide_authentification
    if current_user == nil || current_user.teacher == false
      redirect_to root_path, alert: "You don't have access to this part of the app"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @dive = Dive.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update_teacher_status, :show]

  # new, create, edit, update et destroy sont normalement gérés
  # par Devise dans registrations_controller

  def show
  end

  def update_teacher_status
    if teacher_params[:bio] != "" && teacher_params[:bio] != nil
      @user.bio = teacher_params[:bio]
      @user.teacher = true
      if @user.save
        redirect_to @user
      else
        @modal_open = true
        render :show
      end
    else
      @modal_open = true
      render :show
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def teacher_params
    params.require(:user).permit(:bio)
  end

  # def user_params
  #   params.require(:user).permit(:name, :photo, :level, :bio)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/dives_helper.rb
module DivesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def level_collection
    [["Level 1 : Open Water", 1],
     ["Level 2 : Advanced", 2],
     ["Level 3 : Rescue diver", 3],
     ["Level 4 : Dive guide (can be teacher)", 4],
     ["Level 5 : Dive instructor (can be teacher)", 5]]
  end
end

app/views/bookings/index.html.erb
<%= render 'shared/navbar-left' %>

<h1 class="text-center">Your bookings</h1>

<% @bookings.each do |booking| %>
  <div class="container">
    <div class="row">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path booking.dive.photos.first.path %>;">


        <ul class="list-inline">
          <li><p>You book with <%= booking.dive.user.name %></p></li>
          <li><p><%= cl_image_tag booking.user.photo.path, class: 'avatar' %></p></li>
          <li><%= link_to 'Edit', "#", data: {toggle: "modal", target: "#editBookingModal#{booking.id}"} %></li>
          <li><%= link_to booking.review.present? ? 'Edit your review' : 'Leave a review', "#", data: {toggle: "modal", target: "#reviewModal#{booking.id}"} %></li>
          <li><p><%= link_to "Cancel", user_booking_path(current_user, booking), method: :delete, data: {confirm: "Are you sure you want to cancel this dive?"} %></p></li>
          <li><p><%= link_to "See details of the dive", dive_path(booking.dive) %></p></li>
        </ul>
        <p>Location: <%= booking.dive.location %></p>
        <p>quantity: <%= booking.quantity %> peoples</p>
        <p>Price: <%= booking.quantity * booking.dive.price %></p>
        <p>description: <%= booking.dive.description %> </p>
      </div>
    </div>
  </div>
  <div class="modal fade" id=<%= "editBookingModal#{booking.id}" %> tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="bookingModal">Confirm your dive</h4>
        </div>

        <div class="modal-body">
          <%= simple_form_for [current_user, booking] do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
              <%= f.input :quantity, collection: (1..booking.dive.capacity) %>
              <%= f.hidden_field :dive_id, value: booking.dive.id  %>
            </div>
            <div class="form-actions">
              <%= f.button :submit, "Confirm your book" %>
            </div>

          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id=<%= "reviewModal#{booking.id}" %> tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="bookingModal">What did you think of your dive?</h4>
        </div>

        <div class="modal-body">
          <%= simple_form_for [current_user, booking] do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
              <%= f.input :review %>
              <%= f.input :rating, collection: (0..5) %>
              <%= f.hidden_field :dive_id, value: booking.dive.id  %>
            </div>
            <div class="form-actions">
              <%= f.button :submit, "Leave your review" %>
            </div>

          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/dives/index.html.erb
<h2 class="text-center"> Selectionner votre plongée</h2>


<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <%= render 'shared/search-bar' %>
    </div>
  </div>
  <div class="row card-map">
    <div class="col-xs-12 col-sm-8">
      <div class="row">
        <% @dives.each do |dive| %>
          <div class="col-xs-12 col-sm-6 col-md-4 card">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%=cl_image_path(dive.photos.first.path)%>;">
              <h3><%= dive.location %></h3>
              <p><i class="fa fa-user" aria-hidden="true"></i> <%= dive.capacity %> </p>
              <p>Depth required: <%= dive.depth_required %>meters </p>
              <p><%= dive.price %> € </p>
              <div class="card-user">
                <%= cl_image_tag dive.user.photo.path %>
              </div>

              <%= link_to "", dive_path(dive), class:"card-link"  %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div id="map" style="width: 100%; height: 600px;"></div>

      <% content_for(:after_js) do %>
        <%= javascript_tag do %>
          $(document).ready(function() {
            var handler = Gmaps.build('Google');
            handler.buildMap({ internal: { id: 'map' } }, function() {
              markers = handler.addMarkers(<%= raw @hash.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              if (markers.length == 0) {
                handler.getMap().setZoom(2);
              } else if (markers.length == 1) {
                handler.getMap().setZoom(14);
              }
            });
          });
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/dives/show.html.erb
<div class="container">

  <div class="row text-center">
    <%= cl_image_tag @dive.photos.first.path, :height=>300, :width=>300, :crop=>"imagga_scale", :sign_url=>true %>
    <%= cl_image_tag @dive.photos.last.path, :height=>300, :width=>300, :crop=>"imagga_scale", :sign_url=>true %>
  </div>

  <div class="row description">
    <div class="col-xs-12 col-md-offset-3 col-md-6">
      <h4>A propos de cette plongé</h4>
      <p> <%= @dive.description %> </p>

      <% if current_user == @dive.user%>
      <%= link_to t(".sign_in", default: "Edit your dive"), edit_guide_dive_path, class: "btn btn-primary" %>

      <% elsif user_signed_in? %>
        <button class="btn btn-primary" data-toggle="modal" data-target="#bookingModal">Confirm your dive</button>

      <% else %>
        <%= link_to t(".sign_in", default: "Confirm your dive"), new_user_session_path, class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>

  <div class="col-xs-12 col-md-offset-3 col-md-6">
    <hr>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-offset-3 col-md-6">
      <div class="col-xs-2 col-md-2">
        <h5>location</h5>
      </div>
      <div class="col-xs-10 col-md-10">
        <%= @dive.location %>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-md-offset-3 col-md-6">
    <hr>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-offset-3 col-md-6">
      <div class="col-xs-2 col-md-2">
        <h5>capacity</h5>
      </div>
      <div class="col-xs-10 col-md-10">
        <%= @dive.capacity %>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-md-offset-3 col-md-6">
    <hr>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-offset-3 col-md-6">
      <div class="col-xs-2 col-md-2">
        <h5>price</h5>
      </div>
      <div class="col-xs-10 col-md-10">
        <%= @dive.price %>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-md-offset-3 col-md-6">
    <hr>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-offset-3 col-md-6">
      <div class="col-xs-2 col-md-2">
        <h5>depth required</h5>
      </div>
      <div class="col-xs-10 col-md-10">
        <%= @dive.depth_required %>
      </div>
    </div>
  </div>
</div>

<% if user_signed_in? %>
  <%= render 'shared/booking-modal' %>
<% end %>

<div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <div id="reviews">
      <h2>
        <%= pluralize @dive.bookings.where("review != ''").size, "Review" %>
      </h2>
      <% @dive.bookings.each do |booking| %>
        <% if booking.review.present? && booking.rating.present? %>
          <div class=<%= "card-review review#{booking.id}" %>>
            <%= cl_image_tag booking.user.photo.path, :crop=>"imagga_scale", :sign_url=>true, class: "avatar-large" %>
            <div class="user">
              <p><%= booking.user.name %></p>
            </div>
            <div class="content">
              <p><%= booking.review %></p>
            </div>
            <div class="rating">
              <ul class="list-inline">
                <% booking.rating.times do  %>
                  <li><i class="fa fa-star" style="color: yellow;"></i></li>
                <% end %>
                <% (5 - booking.rating).times do  %>
                  <li><i class="fa fa-star" style="color: #CCC;"></i></li>
              <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/guide/dives/edit.html.erb
<h1 class="text-center">Edit your dive</h1>


<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <div class="edit-form">
        <%= simple_form_for [:guide, @dive] do |f| %>
          <%= f.error_notification %>
          <div class="form-inputs">
            <%= f.input :location %>
            <%= f.input :capacity %>
            <%= f.input :price %>
            <%= f.input :depth_required %>
            <%= f.input :description %>
            <%= f.input :photos, as: :attachinary %>
          </div>
          <div class="form-actions">
            <%= f.button :submit, "Modify your dives" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/guide/dives/index.html.erb
<div class="container">
  <%= render 'shared/navbar-left' %>

  <h1 class="text-center">My list of Dives</h1>

  <div class="card-list-dives">
  <% @dives.each do |dive| %>
    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path dive.photos.first.path %>;">
      <div class="card-category"><%= dive.location %></div>
    <div class="card-description">
      <h2><%= dive.capacity %> <i class="fa fa-user" aria-hidden="true"></i></h2>
      <p>Depth required: <%= dive.depth_required %> meters</p>
      <p><%= dive.price %> €</p>
      <div class="card-user avatar">
        <%= cl_image_tag dive.user.photo.path %>
      </div>
      <ul class="list-inline">
        <li><%= link_to "Edit details", edit_guide_dive_path(dive) %></li>
        <li><%= link_to "See details", dive_path(dive) %></li>
      </ul>
    </div>
   </div>
  <% end %>
  </div>
  <%= link_to "Add a Dive", new_guide_dive_path, { class: "btn btn-primary"} %>
</div>

app/views/guide/dives/new.html.erb
<div class="container">

  <h1>Create a dive</h1>

  <%= simple_form_for [:guide, @dive] do |f| %>
    <%= f.input :location %>
    <%= f.input :capacity %>
    <%= f.input :price %>
    <%= f.input :depth_required %>
    <%= f.input :description %>
    <%= f.input :photos, as: :attachinary %>

    <%= f.submit "Add a dive", class: "btn btn-primary" %>
  <% end %>

  <%= link_to "Back", guide_dives_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Scuba booking</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel="shortcut icon" href="../../assets/images/logo.png">

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div class="bottom-marge"><%= yield %></div>

    <%= render 'shared/footer' %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
 <%= render 'shared/banner' %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path('banner3.jpg') %>');">
  <div class="banner-content">
    <h1>Scuba Booking</h1>
    <h3>Pimp your dive</h3>
    <div class="row">
      <%= render 'shared/search-bar' %>
    </div>
  </div>
</div>

app/views/shared/_booking-modal.html.erb
<div class="modal fade" id="bookingModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="bookingModal">Confirm your dive</h4>
      </div>

      <div class="modal-body">
        <%= simple_form_for [current_user, @booking] do |f| %>
          <%= f.error_notification %>
          <div class="form-inputs">
            <%= f.input :quantity, collection: (1..@dive.capacity) %>
            <div class="date">
              <%= f.input_field :date, as: :string, :"data-dates-disabled" => @unavailability, :"data-provide" => 'datepicker', :"data-date-start-date" => @today, class: 'form-control' %>
            </div>
            <%= f.hidden_field :dive_id, value: @dive.id  %>
          </div>
          <div class="form-actions">
            <%= f.button :submit, "Confirm your book" %>
          </div>

        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar-left.html.erb
<div class="navbar navbar-inverse navbar-fixed-left">
  <ul class="nav navbar-nav">
    <li><%= link_to "Profil", user_path(current_user) %></li>
    <li><%= link_to "Booking", user_bookings_path(current_user) %></li>
    <li><%= link_to "Dives", guide_dives_path %></li>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= 'home' if params[:controller] == 'pages' %>">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
   <!--  <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->
    <% if user_signed_in? && current_user.teacher != true && current_user.level >= 4%>
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
        Become a guide
      </button>
    <% end %>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>


      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

<% if user_signed_in? && current_user.teacher != true %>

  <%= render 'shared/teacher-modal' %>

<% end %>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      <% if @modal_open == true %>
        $('#myModal').modal('show');
      <% end %>
    });
  <% end %>
<% end %>

app/views/shared/_teacher-modal.html.erb
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">To become a teacher, please type your bio here</h4>
        </div>
        <div class="modal-body">
          <%= simple_form_for(current_user, url: teacher_path(current_user)) do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
              <%= f.input :bio %>
            </div>
            <div class="form-actions">
              <%= f.button :submit, "Start your experience" %>
            </div>

          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>